### ISSUE TITLE
Les emmagrammes ne se chargent plus

### ISSUE THREAD

**Issue by Renankasmi** [mmomtchev/velivole#5]
Un petit bug observé: les émagrammes ne se chargent plus 
![image](https://github.com/mmomtchev/velivole/assets/121189702/04b334ab-71b3-4716-8192-b23baab7c42e)
![image](https://github.com/mmomtchev/velivole/assets/121189702/4eaae981-5eeb-4c77-bf2a-077b65c67e60)

**Comment by Renankasmi** [comment]
Désolé pour la faute de frappe dans le titre :)

**Comment by mmomtchev** [comment]
C'est corrigé, le serveur était tombé à court de mémoire et certains services s'étaient bloqués, comme les émagrammes ne sont pas supervisés et je n'ai pas volé pendant qques jours je ne l'avais pas vu
